# Generated by Django 3.2.8 on 2021-11-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=80, verbose_name='Last name')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('sector', models.CharField(max_length=30, verbose_name='Sector')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clentes',
                'ordering': ['first_name'],
            },
        ),
    ]
